apiVersion: v1
kind: PersistentVolume
metadata:
  name: otrs-mineco
  namespace: mineco
  labels:
    otrs: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/deployment/application/otrs/otrs"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otrs-mineco
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      otrs: ready
