apiVersion: v1
kind: PersistentVolume
metadata:
  name: gestion
  namespace: diaco
  labels:
    gestion: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/deployment/gestion"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gestion
  namespace: diaco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      gestion: ready
