apiVersion: v1
kind: PersistentVolume
metadata:
  name: biometrico
  namespace: mineco
  labels:
    biometrico: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/deployment/application/biometrico"
  # nfs:
  #   server: 128.5.105.221
  #   path: "/deployment/application/biometrico"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: biometrico
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      biometrico: ready
