apiVersion: v1
kind: Service
metadata:
  name: quejas
  namespace: mineco-dev
  labels:
    app.kubernetes.io/name: quejas
    app.kubernetes.io/part-of: quejas
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  type: LoadBalancer
  externalIPs:
  - 128.5.9.76
  selector:
    run: quejas
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP