apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-laravel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /app1
        backend:
          serviceName: app-v1
          servicePort: 8080
