# persinsten deploy payara
apiVersion: v1
kind: PersistentVolume
metadata:
  name: payara-deploy
  namespace: mineco
  labels:
    name: payara-deploy
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.105.221
    path: "/deployment/payara/diaco"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payara-deploy
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: payara-deploy