apiVersion: v1
kind: Service
metadata:
  name: ingress-mineco
  namespace: mineco-namespaces
  labels:
    app.kubernetes.io/name: mineco_app
    app.kubernetes.io/part-of: mineco_app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: mineco_app
    app.kubernetes.io/part-of: mineco_app

---
