apiVersion: v1
kind: PersistentVolume
metadata:
  name: mineco-docu-pv
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/dtidesarrollo/comercio"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documentos-mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      mysql: ready
