apiVersion: v1
kind: Service
metadata:
  name: quejaweb
  namespace: mineco
  labels:
    app.kubernetes.io/name: quejaweb
    app.kubernetes.io/part-of: quejaweb
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  type: LoadBalancer
  externalIPs: 
  - 128.5.9.76
  selector:
    run: quejaweb
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP